// Create db variable and get database connection here ...
// Get QueryTypes from sequelize

// Create controller add User here ...

// Create controller get Users here ...

// Create controller get User by received id here ...

// Create controller update User here ...

// Create controller delete User here ...
